version: "3"

services:
    backend:
        build: .
        environment:
            - DB_URL=mongodb://database:27017/nasa
            - PORT=8000
        depends_on:
            - database
        ports:
            - 8000:8000

    database:
        image: mongo
        volumes:
            # named volume to persist data
            - mongo-db:/data/db

volumes:
    mongo-db:
