name: NASA project build & test CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Default checkout action
              uses: actions/checkout@v2
            - name: Use node.js v18
              uses: actions/setup-node@v2
              with:
                  node-version: "18"
            - run: npm install
            - run: npm run build --prefix client
